permissions: write-all # Equivalent to default permissions plus id-token: write
name: "Tests"
env:
  ESC_ACTION_OIDC_AUTH: true
  ESC_ACTION_OIDC_ORGANIZATION: pulumi
  ESC_ACTION_OIDC_REQUESTED_TOKEN_TYPE: urn:pulumi:token-type:access_token:organization
  ESC_ACTION_ENVIRONMENT: imports/github-secrets
  ESC_ACTION_EXPORT_ENVIRONMENT_VARIABLES: GITHUB_TOKEN=PULUMI_BOT_TOKEN

jobs:
  Test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Fetch secrets from ESC
        uses: pulumi/esc-action@v1
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          version: 2025.5.8
      - name: Run Lint
        run: make lint
      - name: Run Tests
        run: make test

on:
  workflow_call:
    secrets:
      PULUMI_BOT_TOKEN:
        required: true
  pull_request:
    branches:
      - main
