name: "Tests"
env:
  GITHUB_TOKEN: ${{ secrets.PULUMI_BOT_TOKEN }}

jobs:
  Test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          version: 2025.5.8
      - name: Run Lint
        run: make lint
      - name: Run Tests
        run: bats --trace --print-output-on-failure test/

on:
  workflow_call:
    secrets:
      PULUMI_BOT_TOKEN:
        required: true
  pull_request:
    branches:
      - main
